import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        'sys-bg-base': '#161616',
        'sys-layer-01': '#262626',
        'sys-layer-02': '#393939',
        'text-primary': '#f4f4f4',
        'text-secondary': '#c6c6c6',
        'text-muted': '#8d8d8d',
        'accent-primary': '#0f62fe',
        'accent-hover': '#0043ce',
        'accent-light': '#78a9ff',
        'ruby-alert': '#da1e28',
        'magenta-glow': '#f96bee',
        // New UI Component Library Tokens
        'bg-primary': 'var(--color-bg-primary)',
        'bg-surface': 'var(--color-bg-surface)',
        'border': 'var(--color-border)',
        'text-main': 'var(--color-text-main)',
        'text-muted-alt': 'var(--color-text-muted)',
        'critical': 'var(--color-critical)',
        'moderate': 'var(--color-moderate)',
        'seasonal': 'var(--color-seasonal)',
        'station': 'var(--color-station)',
        'boundary': 'var(--color-boundary)',
        // Material 3 Tokens from design
        "secondary-fixed-dim": "#c8c6c6",
        "surface-tint": "#b4c5ff",
        "secondary": "#c8c6c6",
        "error": "#ffb4ab",
        "surface-container": "#1d1f28",
        "primary-container": "#0f62fe",
        "on-tertiary": "#5d1900",
        "surface-dim": "#11131c",
        "on-primary": "#002979",
        "surface-variant": "#32343e",
        "outline-variant": "#424656",
        "inverse-primary": "#0052dd",
        "primary-fixed": "#dbe1ff",
        "on-background": "#e1e1ee",
        "surface": "#11131c",
        "on-surface-variant": "#c3c6d8",
        "surface-container-high": "#272a33",
        "on-secondary": "#303030",
        "inverse-on-surface": "#2e303a",
        "primary": "#b4c5ff",
        "on-primary-container": "#f3f3ff",
        "on-tertiary-container": "#fff1ed",
        "surface-container-highest": "#32343e",
        "inverse-surface": "#e1e1ee",
        "on-error": "#690005",
        "on-tertiary-fixed": "#390c00",
        "background": "#11131c",
        "surface-bright": "#373943",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdbd0",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#003da9",
        "secondary-fixed": "#e4e2e1",
        "tertiary": "#ffb59d",
        "surface-container-low": "#191b24",
        "tertiary-container": "#c84000",
        "on-secondary-container": "#b6b5b4",
        "outline": "#8c90a2",
        "on-secondary-fixed": "#1b1c1c",
        "on-primary-fixed": "#00174c",
        "on-tertiary-fixed-variant": "#832700",
        "on-surface": "#e1e1ee",
        "on-secondary-fixed-variant": "#474747",
        "secondary-container": "#474747",
        "surface-container-lowest": "#0b0e16",
        "tertiary-fixed-dim": "#ffb59d",
        "primary-fixed-dim": "#b4c5ff"
      },
      fontFamily: {
        sans: ['var(--font-ibm-plex-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-ibm-plex-mono)', 'monospace'],
        main: ['var(--font-main)'],
      },
      spacing: {
        '8': '8px',
        '16': '16px',
        '24': '24px',
        '32': '32px',
        '48': '48px',
        '64': '64px',
        '96': '96px',
        '128': '128px',
      },
      borderRadius: {
        '4': '4px',
        '6': '6px',
        '8': '8px',
        'md': 'var(--radius-md)',
      },
      boxShadow: {
        'dual': '0 4px 12px rgba(0,0,0,0.4)',
        'elevated': '0 12px 24px -8px rgba(0,0,0,0.6), 0 4px 12px rgba(15,98,254,0.1)',
        'floating': '0 24px 48px -12px rgba(0,0,0,0.8), 0 12px 32px rgba(15,98,254,0.15)',
        'blue-glow': '0 4px 12px rgba(15,98,254,0.3)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
      }
    },
  },
  plugins: [],
};
export default config;